name: Silence
version: 0.6.1.4
main: net.madmanmarkau.Silence.Silence
author: MadManMarkAu, filbert66
license: WTFPL
description: >
             Silence annoying players.
             Allows players to ignore individual players annoying to them.
commands:
  silence_silence:
    description: Silences players.
    aliases: silence
    usage: /<command> <player> [ON|OFF|<seconds>]
    permission:
     - silence.query
     - silence.modify
  silence_silenceall:
    description: Silences all players.
    aliases: silenceall
    usage: /<command> [ON|OFF|<seconds>]
    permission:
     - silence.queryall
     - silence.modifyall
  silence_ignore:
    description: Ignores specific player's chats
    aliases: ignore
    usage: /<command> [<player> [ON|OFF|<seconds>]]
    permission:
      - silence.ignore
 